version: '3.8'
services:
  postgres:
    image: postgres:15-alpine # Kita pakai versi Alpine linux yang super ringan
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: zhaymm_test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: